spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:/czz/tools-workspace/tools/h2/data/test
    username: test
    password: sa
    schema:
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false